# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"drive_setup": "00_core.ipynb",
         "clone_new_repo": "00_core.ipynb",
         "change_dir": "00_core.ipynb",
         "home_dir": "00_core.ipynb",
         "pd.options.display.max_columns": "03_dstemplate.ipynb",
         "pd.options.display.max_rows": "03_dstemplate.ipynb",
         "plotly.offline.init_notebook_mode(connected": "03_dstemplate.ipynb",
         "cf.go_offline(connected": "03_dstemplate.ipynb",
         "cf.set_config_file(theme": "03_dstemplate.ipynb",
         "PARAM": "03_dstemplate.ipynb"}

modules = ["core.py",
           "troubleshooting.py",
           "dstemplate.py"]

doc_url = "https://hallmx.github.io/nbd_colab/"

git_url = "https://github.com/hallmx/nbd_colab/tree/master/"

def custom_doc_links(name): return None
