# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"check_input": "00_core.ipynb",
         "get_dest_dir": "00_core.ipynb",
         "get_repo": "00_core.ipynb",
         "StopExecution": "00_core.ipynb",
         "drive_setup": "00_core.ipynb",
         "change_dir": "00_core.ipynb",
         "home_dir": "00_core.ipynb",
         "run_subprocess": "00_core.ipynb",
         "clone_new_repo": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hallmx.github.io/nbd_colab/"

git_url = "https://github.com/hallmx/nbd_colab/tree/master/"

def custom_doc_links(name): return None
