# AUTOGENERATED! DO NOT EDIT! File to edit: 03_dstemplate.ipynb (unless otherwise specified).

__all__ = ['PARAM']

# Cell

# general
import os, pickle, pathlib

# Data manipulation
import pandas as pd
import numpy as np

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# Visualizations
import matplotlib as plt

import plotly
import plotly.graph_objs as go
import plotly.offline as ply
plotly.offline.init_notebook_mode(connected=True)

import cufflinks as cf
cf.go_offline(connected=True)
cf.set_config_file(theme='white')

# Cell

# Include local library paths
import sys
# sys.path.append('path/to/local/lib') # uncomment and fill to import local libraries

# Import local libraries

# Cell

PARAM = 0